# Generated by Django 4.0 on 2021-12-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_categoria_alter_task_description_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
